# Generated by Django 5.1.1 on 2024-10-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_signup_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='signup_status',
        ),
    ]
