# Generated by Django 5.1.1 on 2024-10-14 12:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_signup_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_type',
        ),
        migrations.AddField(
            model_name='user',
            name='auth_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('PHONE_NUMBER', 'Phone Number')], default='EMAIL', max_length=33),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'heic'])]),
        ),
        migrations.CreateModel(
            name='UserConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('verify_type', models.CharField(choices=[('PHONE_NUMBER', 'Phone Number'), ('EMAIL', 'Email')], max_length=31)),
                ('expire_time', models.DateTimeField(null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verify_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
